services:
  - type: web
    name: llm-quiz-bot-23f2001850
    runtime: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: QUIZ_SECRET
        sync: false
      - key: MAX_QUIZ_TIME
        value: 180
      - key: PORT
        value: 8000
